#!groovy
pipeline {
  agent any
  environment {
        registry = "crystalanvy/dev_docker_1"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
  stages {
    stage('Cloning our Git') {
        steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/crystalanvy/Devops.git']]])
            }
    }
    stage('Docker Build') {
      agent any
      steps{
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
            }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    
  }
}
